# Generated by Django 5.1 on 2024-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_jobrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
